# [![Build Status](https://travis-ci.org/dex4er/perluse.png?branch=master)](https://travis-ci.org/dex4er/perluse)

os: linux
dist: bionic

language: perl

jobs:
  include:
    - env: PERL_VERSION=5.8.9
    - env: PERL_VERSION=5.30.1 DIST_SH=yes

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq spell
  - perlbrew install --notest --noman $PERL_VERSION || true
  - perlbrew use $PERL_VERSION
  - cpanm --with-recommends --installdeps --notest --skip-satisfied .
  - if [ "$DIST_SH" = yes ]; then cpanm --with-recommends --installdeps --notest --skip-satisfied git://github.com/dex4er/perl-DEXTER-Module-Skeleton; fi

script:
  - perl Build.PL
  - perl Build
  - perl Build test
  - if [ "$DIST_SH" = yes ]; then ./Dist.SH; fi
